#!/bin/bash

kill $(lsof -t -i :8000)

if [ ! -f .env ]; then
  cp .env.example .env
  echo "Please add your api keys to the .env file."
fi
yarn
yarn build
yarn start:api > /dev/null 2>&1 &

# Disown the backgrounded process so it's not terminated when the script exits
disown
exit 0
